#!/usr/bin/env bash
#
# Publishes the built release to shared hosting.
#
# Preferred path (SSH enabled): upload the release zip over SFTP, extract on the
# server, then run artisan maintenance. One file transfer is dramatically more
# reliable than mirroring thousands of vendor files over FTPS.
#
# Fallback (SSH disabled): mirror dist/app over FTP(S) with lftp.
#
# Invoked via `tc deploy`, which builds dist/ first and launches this script
# inside the taskconnect-deploy Docker image.
#
set -euo pipefail

CONFIG="${1:-deploy.config.json}"
LOCAL_DIR="dist/app"
LOCAL_ZIP="dist/taskconnect-release.zip"

log() { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33mWarning:\033[0m %s\n' "$*" >&2; }
err() { printf '\033[1;31mError:\033[0m %s\n' "$*" >&2; }

if ! command -v jq >/dev/null 2>&1; then
  err "jq is required but not available in this image."
  exit 1
fi

if [[ ! -f "$CONFIG" ]]; then
  err "Config file not found: $CONFIG"
  err "Copy deploy.config.example.json to deploy.config.json and fill in your credentials."
  exit 1
fi

j() { jq -r "$1" "$CONFIG"; }

SITE="$(j '.site // empty')"
INJECT_HTACCESS="$(j '.options.inject_root_htaccess // true')"
UPLOAD_ENV="$(j '.options.upload_env // false')"
ENV_SOURCE="$(j '.options.env_source // ".env.production"')"
DELETE_REMOTE="$(j '.options.delete_remote // false')"

SSH_ENABLED="$(j '.ssh.enabled // false')"
SSH_HOST="$(j '.ssh.host // empty')"
SSH_PORT="$(j '.ssh.port // 22')"
SSH_USER="$(j '.ssh.username // empty')"
SSH_PASS="$(j '.ssh.password // empty')"
APP_DIR="$(j '.ssh.app_dir // empty')"
PHP_BIN="$(j '.ssh.php_binary // "php"')"
RUN_MIGRATIONS="$(j '.ssh.run_migrations // false')"
RUN_OPTIMIZE="$(j '.ssh.run_optimize // true')"
STORAGE_LINK="$(j '.ssh.storage_link // true')"

FTP_HOST="$(j '.ftp.host // empty')"
FTP_PORT="$(j '.ftp.port // 21')"
FTP_USER="$(j '.ftp.username // empty')"
FTP_PASS="$(j '.ftp.password // empty')"
FTP_SECURE="$(j '.ftp.secure // true')"
FTP_VERIFY="$(j '.ftp.verify_certificate // false')"
REMOTE_DIR="$(j '.ftp.remote_dir // empty')"

run_ssh() {
  sshpass -p "${SSH_PASS}" ssh \
    -o StrictHostKeyChecking=no \
    -o UserKnownHostsFile=/dev/null \
    -o LogLevel=ERROR \
    -o ServerAliveInterval=30 \
    -p "${SSH_PORT}" \
    "${SSH_USER}@${SSH_HOST}" \
    "$@"
}

run_scp() {
  sshpass -p "${SSH_PASS}" scp \
    -C \
    -o StrictHostKeyChecking=no \
    -o UserKnownHostsFile=/dev/null \
    -o LogLevel=ERROR \
    -o ServerAliveInterval=15 \
    -o ServerAliveCountMax=8 \
    -o TCPKeepAlive=yes \
    -P "${SSH_PORT}" \
    "$@"
}

inject_htaccess() {
  local target_dir="$1"
  if [[ "$INJECT_HTACCESS" != "true" ]]; then
    return 0
  fi

  log "Injecting hardened root .htaccess into ${target_dir}"
  cat > "${target_dir}/.htaccess" <<'HTACCESS'
# Auto-generated by scripts/deploy.sh. Routes all traffic into public/ so the
# rest of the Laravel application stays non-executable behind the front
# controller. Because every non-/public/ request is rewritten into public/,
# the source directories (app/, config/, vendor/, .env, ...) are never served
# directly even though they physically live under this document root.
<IfModule mod_rewrite.c>
    RewriteEngine On

    # Hard-deny dotfiles that must never be exposed under any circumstance.
    RewriteRule (^|/)\.(?!well-known)([^/]+) - [F,L]

    # Send everything else through the public/ front controller.
    RewriteCond %{REQUEST_URI} !^/public/
    RewriteRule ^(.*)$ public/$1 [L]
</IfModule>
HTACCESS
}

deploy_via_ssh() {
  if [[ ! -f "$LOCAL_ZIP" ]]; then
    err "Release zip missing at $LOCAL_ZIP. Build it first via 'tc deploy'."
    exit 1
  fi
  if [[ -z "$SSH_HOST" || -z "$SSH_USER" || -z "$APP_DIR" ]]; then
    err "ssh.host, ssh.username and ssh.app_dir are required when SSH is enabled."
    exit 1
  fi

  # Ensure the local tree has the hardened .htaccess before we re-pack a
  # deploy-only zip that includes it (the release zip itself is left intact).
  if [[ -d "$LOCAL_DIR" ]]; then
    inject_htaccess "$LOCAL_DIR"
  fi

  local staging_zip="/tmp/taskconnect-deploy.zip"
  if [[ -d "$LOCAL_DIR" ]]; then
    log "Packaging deploy zip from ${LOCAL_DIR} (includes .htaccess)"
    (cd "$LOCAL_DIR" && zip -qr "$staging_zip" .)
  else
    log "Using release zip ${LOCAL_ZIP}"
    cp "$LOCAL_ZIP" "$staging_zip"
  fi

  local remote_tmp="${APP_DIR}/.taskconnect-release.zip"
  local remote_size
  remote_size="$(stat -c%s "$staging_zip" 2>/dev/null || wc -c < "$staging_zip")"
  log "Uploading release zip ($(numfmt --to=iec "$remote_size" 2>/dev/null || echo "${remote_size} bytes")) over SFTP to ${SSH_HOST}:${SSH_PORT}"

  local attempt=1
  local max_attempts=3
  until run_scp "$staging_zip" "${SSH_USER}@${SSH_HOST}:${remote_tmp}"; do
    if (( attempt >= max_attempts )); then
      err "SFTP upload failed after ${max_attempts} attempts."
      exit 1
    fi
    warn "SFTP upload attempt ${attempt} failed; retrying in 5s..."
    sleep 5
    attempt=$((attempt + 1))
  done

  if [[ "$UPLOAD_ENV" == "true" ]]; then
    if [[ -f "$ENV_SOURCE" ]]; then
      log "Uploading ${ENV_SOURCE} -> ${APP_DIR}/.env (via SSH pipe)"
      # Prefer piping over a second SCP — Hostinger often drops rapid successive
      # SCP sessions. Strip CR in case the file was edited on Windows.
      local env_attempt=1
      until tr -d '\r' < "$ENV_SOURCE" | run_ssh "cat > $(printf '%q' "${APP_DIR}/.env")"; do
        if (( env_attempt >= 3 )); then
          err ".env upload failed after 3 attempts."
          exit 1
        fi
        warn ".env upload attempt ${env_attempt} failed; retrying in 5s..."
        sleep 5
        env_attempt=$((env_attempt + 1))
      done
    else
      warn "options.upload_env is true but ${ENV_SOURCE} was not found; skipping .env upload."
    fi
  fi

  log "Extracting on the server and running maintenance"
  # shellcheck disable=SC2087
  run_ssh bash -s <<REMOTE
set -euo pipefail
APP_DIR=$(printf '%q' "$APP_DIR")
REMOTE_TMP=$(printf '%q' "$remote_tmp")
PHP_BIN=$(printf '%q' "$PHP_BIN")
DELETE_REMOTE=$(printf '%q' "$DELETE_REMOTE")
RUN_MIGRATIONS=$(printf '%q' "$RUN_MIGRATIONS")
RUN_OPTIMIZE=$(printf '%q' "$RUN_OPTIMIZE")
STORAGE_LINK=$(printf '%q' "$STORAGE_LINK")

cd "\$APP_DIR"

# Drop leftover FTPS temp files from any previous interrupted mirror.
find . -type f -name '.in.*' -delete 2>/dev/null || true

# Preserve runtime state across deploys.
mkdir -p /tmp/tc-preserve
if [[ -f .env && "${UPLOAD_ENV}" != "true" ]]; then
  cp .env /tmp/tc-preserve/.env
fi
if [[ -d storage ]]; then
  cp -a storage /tmp/tc-preserve/storage
fi
if [[ -d bootstrap/cache ]]; then
  mkdir -p /tmp/tc-preserve/bootstrap
  cp -a bootstrap/cache /tmp/tc-preserve/bootstrap/cache
fi

if [[ "\$DELETE_REMOTE" == "true" ]]; then
  find . -mindepth 1 -maxdepth 1 \
    ! -name '.taskconnect-release.zip' \
    ! -name '.env' \
    ! -name '.' \
    -exec rm -rf {} +
fi

# Prefer unzip; fall back to php's ZipArchive if unzip is unavailable.
if command -v unzip >/dev/null 2>&1; then
  unzip -qo "\$REMOTE_TMP" -d "\$APP_DIR"
elif "\$PHP_BIN" -r 'exit(class_exists("ZipArchive")?0:1);'; then
  "\$PHP_BIN" -r '
    \$zip = new ZipArchive();
    if (\$zip->open(\$argv[1]) !== true) { fwrite(STDERR, "Unable to open zip\n"); exit(1); }
    \$zip->extractTo(\$argv[2]);
    \$zip->close();
  ' "\$REMOTE_TMP" "\$APP_DIR"
else
  echo "Neither unzip nor PHP ZipArchive is available on the server." >&2
  exit 1
fi

rm -f "\$REMOTE_TMP"

# Restore preserved runtime state.
if [[ -f /tmp/tc-preserve/.env ]]; then
  cp /tmp/tc-preserve/.env .env
fi
if [[ -d /tmp/tc-preserve/storage ]]; then
  # Overlay previous storage (logs, uploaded files, framework cache) onto the
  # freshly extracted tree without wiping the new empty skeleton dirs.
  cp -a /tmp/tc-preserve/storage/. storage/ 2>/dev/null || true
fi
if [[ -d /tmp/tc-preserve/bootstrap/cache ]]; then
  mkdir -p bootstrap/cache
  cp -a /tmp/tc-preserve/bootstrap/cache/. bootstrap/cache/ 2>/dev/null || true
fi
rm -rf /tmp/tc-preserve

mkdir -p storage/framework/{cache,sessions,views} storage/logs bootstrap/cache
chmod -R ug+rwX storage bootstrap/cache 2>/dev/null || true

echo "Remote PHP: \$(\$PHP_BIN -v | head -n1)"

if [[ ! -f .env ]]; then
  echo "WARNING: .env is missing on the server. Create it before running migrations." >&2
fi

# Migrate before any cache clear that touches the DB cache store.
if [[ "\$RUN_MIGRATIONS" == "true" ]]; then
  "\$PHP_BIN" artisan migrate --force
fi
if [[ "\$STORAGE_LINK" == "true" ]]; then
  # Hostinger disables PHP exec(); create the symlink with ln instead of artisan.
  mkdir -p storage/app/public
  ln -sfn ../storage/app/public public/storage || true
fi
if [[ "\$RUN_OPTIMIZE" == "true" ]]; then
  "\$PHP_BIN" artisan optimize:clear || true
  "\$PHP_BIN" artisan config:cache || true
  "\$PHP_BIN" artisan route:cache || true
fi

echo "Remote maintenance complete."
REMOTE
}

deploy_via_ftp() {
  if [[ ! -d "$LOCAL_DIR" ]]; then
    err "Release tree missing at $LOCAL_DIR."
    exit 1
  fi
  if [[ -z "$FTP_HOST" || -z "$REMOTE_DIR" ]]; then
    err "ftp.host and ftp.remote_dir are required for FTP deploy."
    exit 1
  fi

  inject_htaccess "$LOCAL_DIR"

  local ssl_settings
  if [[ "$FTP_SECURE" == "true" ]]; then
    ssl_settings="set ftp:ssl-force true; set ftp:ssl-protect-data true;"
  else
    ssl_settings="set ftp:ssl-allow false;"
  fi

  local delete_flag=""
  if [[ "$DELETE_REMOTE" == "true" ]]; then
    delete_flag="--delete"
  fi

  log "Uploading ${LOCAL_DIR} -> ${FTP_HOST}:${REMOTE_DIR} (secure=${FTP_SECURE}, delete=${DELETE_REMOTE})"

  # Disable temp files (.in.*) — Hostinger shared FTP often leaves them behind
  # when parallel transfers are interrupted, blocking subsequent deploys.
  lftp <<LFTP
set cmd:fail-exit true;
set net:max-retries 3;
set net:timeout 25;
set net:reconnect-interval-base 5;
set xfer:use-temp-file false;
set xfer:clobber true;
set ftp:ssl-force ${FTP_SECURE};
${ssl_settings}
set ssl:verify-certificate ${FTP_VERIFY};
open -p ${FTP_PORT} -u "${FTP_USER}","${FTP_PASS}" ftp://${FTP_HOST};
mirror -R ${delete_flag} --parallel=2 --no-perms \
  --exclude-glob .env \
  --exclude-glob .env.* \
  --exclude-glob .git* \
  --exclude-glob storage/logs/*.log \
  --exclude-glob .in.* \
  "${LOCAL_DIR}/" "${REMOTE_DIR}";
bye;
LFTP

  log "File upload complete."

  if [[ "$UPLOAD_ENV" == "true" ]]; then
    if [[ -f "$ENV_SOURCE" ]]; then
      log "Uploading ${ENV_SOURCE} -> ${REMOTE_DIR}/.env"
      lftp <<LFTP
set cmd:fail-exit true;
set xfer:use-temp-file false;
set ftp:ssl-force ${FTP_SECURE};
${ssl_settings}
set ssl:verify-certificate ${FTP_VERIFY};
open -p ${FTP_PORT} -u "${FTP_USER}","${FTP_PASS}" ftp://${FTP_HOST};
cd "${REMOTE_DIR}";
put "${ENV_SOURCE}" -o .env;
bye;
LFTP
    else
      warn "options.upload_env is true but ${ENV_SOURCE} was not found; skipping .env upload."
    fi
  fi
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
if [[ "$SSH_ENABLED" == "true" ]]; then
  deploy_via_ssh
else
  deploy_via_ftp
  log "SSH disabled; skipping remote migrations. Run 'php artisan migrate --force' on the server manually if needed."
fi

if [[ -n "$SITE" ]]; then
  log "Deployment finished successfully -> https://${SITE}"
else
  log "Deployment finished successfully."
fi
