#!/usr/bin/env bash
#
# Publishes the built release tree (dist/app) to shared hosting over FTP(S)
# and, when SSH is enabled, runs post-deploy maintenance commands remotely.
#
# This runs *inside* the taskconnect-deploy Docker image (lftp/ssh/sshpass/jq),
# so no FTP or SSH client needs to be installed on the host. It is normally
# invoked via `tc deploy`, which builds dist/app first and then launches the
# container with the repository mounted at /work.
#
set -euo pipefail

CONFIG="${1:-deploy.config.json}"
LOCAL_DIR="dist/app"

log() { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
err() { printf '\033[1;31mError:\033[0m %s\n' "$*" >&2; }

if ! command -v jq >/dev/null 2>&1; then
  err "jq is required but not available in this image."
  exit 1
fi

if [[ ! -f "$CONFIG" ]]; then
  err "Config file not found: $CONFIG"
  err "Copy deploy.config.example.json to deploy.config.json and fill in your credentials."
  exit 1
fi

if [[ ! -d "$LOCAL_DIR" ]]; then
  err "Release tree missing at $LOCAL_DIR."
  err "Build it first (the 'tc deploy' verb does this automatically via docker build)."
  exit 1
fi

j() { jq -r "$1" "$CONFIG"; }

FTP_HOST="$(j '.ftp.host')"
FTP_PORT="$(j '.ftp.port // 21')"
FTP_USER="$(j '.ftp.username')"
FTP_PASS="$(j '.ftp.password')"
FTP_SECURE="$(j '.ftp.secure // true')"
FTP_VERIFY="$(j '.ftp.verify_certificate // false')"
REMOTE_DIR="$(j '.ftp.remote_dir')"

DELETE_REMOTE="$(j '.options.delete_remote // false')"
INJECT_HTACCESS="$(j '.options.inject_root_htaccess // true')"
UPLOAD_ENV="$(j '.options.upload_env // false')"
ENV_SOURCE="$(j '.options.env_source // ".env.production"')"

if [[ -z "$FTP_HOST" || "$FTP_HOST" == "null" ]]; then
  err "ftp.host is required in $CONFIG"
  exit 1
fi
if [[ -z "$REMOTE_DIR" || "$REMOTE_DIR" == "null" ]]; then
  err "ftp.remote_dir is required in $CONFIG"
  exit 1
fi

# ---------------------------------------------------------------------------
# Inject a root .htaccess so the whole app can live inside public_html while
# only exposing the Laravel front controller under public/. Sensitive folders
# and dotfiles are blocked outright.
# ---------------------------------------------------------------------------
if [[ "$INJECT_HTACCESS" == "true" ]]; then
  log "Injecting hardened root .htaccess into $LOCAL_DIR"
  cat > "$LOCAL_DIR/.htaccess" <<'HTACCESS'
# Auto-generated by scripts/deploy.sh. Routes all traffic into public/ so the
# rest of the Laravel application stays non-executable behind the front
# controller. Because every non-/public/ request is rewritten into public/,
# the source directories (app/, config/, vendor/, .env, ...) are never served
# directly even though they physically live under this document root.
<IfModule mod_rewrite.c>
    RewriteEngine On

    # Hard-deny dotfiles that must never be exposed under any circumstance.
    RewriteRule (^|/)\.(?!well-known)([^/]+) - [F,L]

    # Send everything else through the public/ front controller.
    RewriteCond %{REQUEST_URI} !^/public/
    RewriteRule ^(.*)$ public/$1 [L]
</IfModule>
HTACCESS
fi

# ---------------------------------------------------------------------------
# FTP(S) upload
# ---------------------------------------------------------------------------
if [[ "$FTP_SECURE" == "true" ]]; then
  SSL_SETTINGS="set ftp:ssl-force true; set ftp:ssl-protect-data true;"
else
  SSL_SETTINGS="set ftp:ssl-allow false;"
fi

DELETE_FLAG=""
if [[ "$DELETE_REMOTE" == "true" ]]; then
  DELETE_FLAG="--delete"
fi

log "Uploading $LOCAL_DIR -> ${FTP_HOST}:${REMOTE_DIR} (secure=${FTP_SECURE}, delete=${DELETE_REMOTE})"

lftp <<LFTP
set cmd:fail-exit true;
set net:max-retries 3;
set net:timeout 25;
set net:reconnect-interval-base 5;
set ftp:ssl-force ${FTP_SECURE};
${SSL_SETTINGS}
set ssl:verify-certificate ${FTP_VERIFY};
open -p ${FTP_PORT} -u "${FTP_USER}","${FTP_PASS}" ftp://${FTP_HOST};
mirror -R ${DELETE_FLAG} --parallel=4 --no-perms \
  --exclude-glob .env \
  --exclude-glob .env.* \
  --exclude-glob .git* \
  --exclude-glob storage/logs/*.log \
  "${LOCAL_DIR}/" "${REMOTE_DIR}";
bye;
LFTP

log "File upload complete."

# ---------------------------------------------------------------------------
# Optionally upload a production .env (never overwrites unless explicitly enabled)
# ---------------------------------------------------------------------------
if [[ "$UPLOAD_ENV" == "true" ]]; then
  if [[ -f "$ENV_SOURCE" ]]; then
    log "Uploading ${ENV_SOURCE} -> ${REMOTE_DIR}/.env"
    lftp <<LFTP
set cmd:fail-exit true;
set ftp:ssl-force ${FTP_SECURE};
${SSL_SETTINGS}
set ssl:verify-certificate ${FTP_VERIFY};
open -p ${FTP_PORT} -u "${FTP_USER}","${FTP_PASS}" ftp://${FTP_HOST};
cd "${REMOTE_DIR}";
put "${ENV_SOURCE}" -o .env;
bye;
LFTP
  else
    err "options.upload_env is true but ${ENV_SOURCE} was not found; skipping .env upload."
  fi
fi

# ---------------------------------------------------------------------------
# SSH post-deploy commands
# ---------------------------------------------------------------------------
SSH_ENABLED="$(j '.ssh.enabled // false')"
if [[ "$SSH_ENABLED" == "true" ]]; then
  SSH_HOST="$(j '.ssh.host')"
  SSH_PORT="$(j '.ssh.port // 22')"
  SSH_USER="$(j '.ssh.username')"
  SSH_PASS="$(j '.ssh.password')"
  APP_DIR="$(j '.ssh.app_dir')"
  PHP_BIN="$(j '.ssh.php_binary // "php"')"
  RUN_MIGRATIONS="$(j '.ssh.run_migrations // false')"
  RUN_OPTIMIZE="$(j '.ssh.run_optimize // true')"
  STORAGE_LINK="$(j '.ssh.storage_link // true')"

  remote_cmds="set -e; cd \"${APP_DIR}\";"
  remote_cmds="${remote_cmds} echo 'Remote PHP:' && ${PHP_BIN} -v | head -n1;"
  if [[ "$RUN_OPTIMIZE" == "true" ]]; then
    remote_cmds="${remote_cmds} ${PHP_BIN} artisan optimize:clear;"
  fi
  if [[ "$RUN_MIGRATIONS" == "true" ]]; then
    remote_cmds="${remote_cmds} ${PHP_BIN} artisan migrate --force;"
  fi
  if [[ "$STORAGE_LINK" == "true" ]]; then
    remote_cmds="${remote_cmds} ${PHP_BIN} artisan storage:link || true;"
  fi
  if [[ "$RUN_OPTIMIZE" == "true" ]]; then
    remote_cmds="${remote_cmds} ${PHP_BIN} artisan config:cache && ${PHP_BIN} artisan route:cache || true;"
  fi

  log "Running post-deploy commands over SSH on ${SSH_HOST}:${SSH_PORT}"
  sshpass -p "${SSH_PASS}" ssh \
    -o StrictHostKeyChecking=no \
    -o UserKnownHostsFile=/dev/null \
    -o LogLevel=ERROR \
    -p "${SSH_PORT}" \
    "${SSH_USER}@${SSH_HOST}" \
    "${remote_cmds}"

  log "Remote maintenance complete."
else
  log "SSH disabled; skipping remote migrations. Run 'php artisan migrate --force' on the server manually if needed."
fi

log "Deployment finished successfully -> https://$(j '.site // .ftp.host')"
